version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: jrobertzz/frontend_poc
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    ports:
      - "443:443"
    networks:
      - webnet

  mysqldb:
    image: sinenomine/mariadb-s390x
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_USER=test_user
      - MYSQL_PASSWORD=test_pass
    ports:
      - "3306:3306"
    volumes:
      - "/data/mysql:/data/mysql"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet

  visualizer:
    image: sinenomine/visualizer-s390x
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
networks:
  webnet:
